name: Comment as Specific User

on:
  pull_request:
    types: [opened]

jobs:
  comment-as-user:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment as specific user
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MY_SECRET_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello @${{ github.actor }},
            
            Thank you for your contribution! Please ensure that:
            - Your PR follows the contribution guidelines.
            - You have added or updated relevant documentation/tests.

            We'll review your PR soon. 😊
